spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://152.136.94.85:3306/bupt_iot?characterEncoding=utf-8&useSSL=false&useUnicode=true
  jpa:
    show-sql: true
  redis:
    port: 6379
    host: 127.0.0.1
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    cache: true
  mvc:
    static-path-pattern: /**
