spring:
  data:
    cassandra:
      cluster-name: Test Cluster
      keyspace-name: test
      contact-points: 188.131.224.206
      port: 9042
      username: cassandra
      password: cassandra
  mqtt:
    client:
      id: devices-access
    default:
      topic: demo_01
    username: admin
    password: public
    url: tcp://127.0.0.1:1883
    completionTimeout: 3000
