spring:
  data:
    cassandra:
      cluster-name: Test Cluster
      keyspace-name: test
      contact-points: 188.131.224.206
      port: 9042
      username: cassandra
      password: cassandra
mqtt:
  host: tcp://152.136.94.85:1883
  client-id: devices-access
  username: bupt-Iot
  password: bupt-Iot
  topic: /device/status,/device/upload
  timeout: 1000
  keepalive: 2000
