spring:
  data:
    cassandra:
      cluster-name: Test Cluster
      keyspace-name: test
      contact-points: 188.131.224.206
      port: 9042
      username: cassandra
      password: cassandra
eureka:
  client:
    service-url:
      defaultZone: http://114.115.130.42:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: 114.115.130.42:${server.port}
server:
  port: 8083
