spring:
  redis:
    port: 6379
    host: 152.136.94.85
zuul:
  routes:
    client:
      path: /**
      serviceId: account
    devices-access:
      path: /**
      serviceId: devices-access
  sensitive-headers:
  ignored-patterns:
  - /client/env
  - /client/login
