spring:
  redis:
    port: 6379
    host: 152.136.94.85
zuul:
  routes:
    account:
      path: /**
      serviceId: account
      stripPrefix: false
    devices-access:
      path: /**
      serviceId: devices-access
      stripPrefix: false
  sensitive-headers:
  ignored-patterns:
  - /account/env
