spring:
  redis:
    port: 6379
    host: 152.136.94.85
zuul:
  routes:
    account:
      path: /api/**
      serviceId: account
      stripPrefix: true
    devices-access:
      path: /devices-access/**
      serviceId: devices-access
      stripPrefix: true
  sensitive-headers:
  ignored-patterns:
  - /account/env
